[package]
name = "playing_with_bevy_and_blender"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.0" }
stl_io = "0.7.0"
bevy_mod_picking = "0.17.0"
wasm-bindgen = "0.2.67" ## add this

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
